services:
  postgres-users:
    image: postgres:18
    container_name: postgres-users
    environment:
      POSTGRES_DB: grind
      POSTGRES_USER: grind
      POSTGRES_PASSWORD: grind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  postgres-core:
    image: postgres:18
    container_name: postgres-core
    environment:
      POSTGRES_DB: grind_core
      POSTGRES_USER: grind_core
      POSTGRES_PASSWORD: grind_core
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_core:/var/lib/postgresql

  # KAFKA
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"   # внешний для хоста
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka_data:/var/lib/kafka/data

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      CMD_ARGS: "--server.port=9000"
    depends_on:
      - kafka

  # SECURITY
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      - postgres-users
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-users
      KC_DB_URL_DATABASE: grind
      KC_DB_USERNAME: grind
      KC_DB_PASSWORD: grind
      KC_HOSTNAME: localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: administrator
      KC_BOOTSTRAP_ADMIN_PASSWORD: administrator

    #      KC_DB_URL: jdbc:postgresql://postgres:5432/grind
    ports:
      - "8085:8080"
    command: [ "start-dev" ]


  # STATISTICS
  clickhouse:
    build:
      context: ./clickhouse
    image: grind/clickhouse-dev:0.1
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP
      - "9001:9000"   # TCP (для клиентов и драйверов)
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

    environment:
      CLICKHOUSE_USER: grind
      CLICKHOUSE_PASSWORD: grind
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
      CLICKHOUSE_MAX_SERVER_MEMORY_USAGE: "1073741824"      # 1ГБ
      CLICKHOUSE_MAX_SERVER_MEMORY_USAGE_TO_RAM_RATIO: "0.5"

volumes:
  kafka_data:
  clickhouse_data:
  postgres_data:
  postgres_data_core:
