spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "http://localhost:3000"
                allowed-methods: "*"
                allowed-headers: "*"
                allow-credentials: true
          routes:
            - id: core
              uri: http://localhost:8083
              predicates:
                - Path=/core/**
                - Method=POST,PUT,DELETE
            - id: database
              uri: http://localhost:8082
              predicates:
                - Path=/database/**
                - Method=GET

server:
  port: 8080