spring:
  application:
    name: api-gateway
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer


grind:
  auth:
    token-endpoint-enabled: true

kafka.topic:
  core:
    request:
      task: 'core.request.task'
      track: 'core.request.track'
    event:
      task: 'core.event.task'
      track: 'core.event.track'
  statistics:
    request: 'statistics.request'
  response: 'response'

server:
  port: 8080