spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "http://localhost:3000"
                allowed-methods: "*"
                allowed-headers: "*"
                allow-credentials: true
          routes:
            - id: core
              uri: http://localhost:8083
              predicates:
                - Path=/core/**
            - id: statistics
              uri: http://localhost:8084
              predicates:
                - Path=/database/**
            - id: auth
              uri: http://localhost:8086
              predicates:
                - Path=/grind/keycloak/**

server:
  port: 8080