spring:
  application:
    name: statistics
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: core-consumer-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 200
      properties:
        max.poll.interval.ms: 600000
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: beans, health, info, mappings
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

clickhouse:
  baseUrl: http://localhost:8123/
  username: grind
  password: grind

kafka.topic:
  core:
    request:
      task: 'core.requestInsert.task'
      track: 'core.requestInsert.track'
    event:
      task: 'core.event.task'
      track: 'core.event.track'
  statistics:
    request: 'statistics.request'
    event: 'statistics.event'
  response: 'response'

server:
  port: 8084
