spring:
  application:
    name: security-library
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8085/realms/grind}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8085/realms/grind/protocol/openid-connect/certs}
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID:grind_client}
            client-secret: ${CLIENT_SECRET:b5fk9Hdmxn7kFgJDao2SFFkfVoypa60g}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/keycloak"
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8085/realms/grind}
            user-name-attribute: preferred_username

keycloak:
  url:
    public: ${KEYCLOAK_LOGIN_URL:http://localhost:8085/realms/grind/protocol/openid-connect}
    admin: ${KEYCLOAK_ADMIN_URL:http://localhost:8085/admin/realms/grind}
  admin-username: ${KEYCLOAK_CLIENT_ADMIN:administrator}
  admin-password: ${KEYCLOAK_CLIENT_PASSWORD:admin}

server:
  port: 8081