spring:
  application:
    name: core
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: core-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: beans, health, info, mappings
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true

kafka.topic:
  core:
    request:
      task: 'core.request.task'
      track: 'core.request.track'
    events:
      task: 'core.event.task'
      track: 'core.event.track'
  statistics:
    request: 'statistics.request'
  response: 'response'

server:
  port: 8083