spring:
  application:
    name: core
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: beans, health, info, mappings
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: core-consumer-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka.topic.core:
  events: 'core.events'
  request: 'core.request'

server:
  port: 8083